version: "3"

services:
  v2ray:
    image: v2ray/official
    container_name: timvel-v2ray
    ports:
      - 8088:8888
    volumes:
      - "./v2ray:/etc/v2ray"
    command: ["v2ray", "-config=/etc/v2ray/config.json"]
    restart: "always"
